/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a Tcs3400Data8Message
 */
public class Tcs3400Data8Message extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int TCS_3400_DATA_8_MESSAGE_MAX_ORDINAL = 4;

	private static final int TCS_3400_DATA_8_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int TCS_3400_DATA_8_MESSAGE_DATA_INDEX = 9;
	private static final int TCS_3400_DATA_8_MESSAGE_PARAM_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int TCS_3400_DATA_8_MESSAGE_DATA_ORDINAL = 4;
	private static final int TCS_3400_DATA_8_MESSAGE_PARAM_ORDINAL = 3;

	//Bit Nums
	/**
	 * A constructor to create a Tcs3400Data8Message.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to pass 8-bit data from the tcs3400 colour sensor into blueberry studio
	 * @param buf - the message buffer to add the message to
	 */
	private Tcs3400Data8Message(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a Tcs3400Data8Message for transmission.
	 * A message to pass 8-bit data from the tcs3400 colour sensor into blueberry studio
	 * @param buf - the message buffer to add the message to
	 * @param param - An enum for defining the available 8-bit parameters of the tcs3400
	 * @param data
	 */
	public static Tcs3400Data8Message make(BlueberryBuffer buf, Parameter8Enum param, int data) {
		Tcs3400Data8Message msg = new Tcs3400Data8Message(buf);
		msg.setupHeader(TCS_3400_DATA_8_MESSAGE_KEY, TCS_3400_DATA_8_MESSAGE_MAX_ORDINAL, TCS_3400_DATA_8_MESSAGE_LENGTH);
		msg.m_buf.writeUint8(TCS_3400_DATA_8_MESSAGE_PARAM_INDEX, param.getValue());
		msg.m_buf.writeUint8(TCS_3400_DATA_8_MESSAGE_DATA_INDEX, data);
		return msg;
	}
	/**
	 * A constructor to create an empty Tcs3400Data8Message for transmission.
	 * A message to pass 8-bit data from the tcs3400 colour sensor into blueberry studio
	 * @param buf - the message buffer to add the message to
	 */
	public static Tcs3400Data8Message makeEmpty(BlueberryBuffer buf) {
		Tcs3400Data8Message msg = new Tcs3400Data8Message(buf);
		msg.setupHeader(TCS_3400_DATA_8_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a Tcs3400Data8Message.
	 * A message to pass 8-bit data from the tcs3400 colour sensor into blueberry studio
	 * @param buf - the message buffer to add the message to
	 */
	public static Tcs3400Data8Message wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, TCS_3400_DATA_8_MESSAGE_KEY)){
			return null;
		}
		Tcs3400Data8Message msg = new Tcs3400Data8Message(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to pass 8-bit data from the tcs3400 colour sensor into blueberry studio
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= TCS_3400_DATA_8_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the param field
	 * An enum for defining the available 8-bit parameters of the tcs3400
	 */
	public Parameter8Enum getParam(){
		int i = 0;
		i = i + TCS_3400_DATA_8_MESSAGE_PARAM_INDEX;
		return Parameter8Enum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the param field
	 * An enum for defining the available 8-bit parameters of the tcs3400
	 */
	boolean isParamPresent(){
		return TCS_3400_DATA_8_MESSAGE_PARAM_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the data field
	 */
	public int getData(){
		int i = 0;
		i = i + TCS_3400_DATA_8_MESSAGE_DATA_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * Tests if the current message containts the data field
	 */
	boolean isDataPresent(){
		return TCS_3400_DATA_8_MESSAGE_DATA_ORDINAL <= (getMaxOrdinal());
	}
}
